name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Clone Flutter repository with stable channel
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.13.1"
        channel: 'stable'
    - name: Get dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter analyze
    # - run: flutter format --set-exit-if-changed --dry-run .
